import { isAudioUrl } from '../api/media';
import MediaPicker from './MediaPicker';
import type { EditorQuestion, EditorQuiz } from '../api/contentQuiz';
import { TranslationFields, emptyTranslation } from './ContentBlocksEditor';
import { useLanguage } from '../i18n/LanguageProvider';
const kinds = { choice: 'Выбор ответа', match: 'Сопоставление пар', order: 'Порядок слов', gap: 'Заполнение пропуска', input: 'Свободный ввод', dictation: 'Диктант' };
const inputClass = 'block w-full border border-border bg-background rounded-lg p-2';
const option = () => ({ id: crypto.randomUUID(), text: emptyTranslation() });
function newQuestion(kind: EditorQuestion['kind']): EditorQuestion {
  const common = { id: crypto.randomUUID(), prompt: emptyTranslation(), explanation: emptyTranslation() };
  const options = [option(), option()];
  if (kind === 'choice') return { ...common, kind, options, correct: options[0].id };
  if (kind === 'order') return { ...common, kind, options, correct: options.map(o => o.id) };
  if (kind === 'match') return { ...common, kind, left: [option(), option()], right: options, correct: options.map(o => o.id) };
  if (kind === 'dictation') return { ...common, kind, accepted: [''], audioUrl: '', sourceUrl: '', author: '', license: '', licenseUrl: '' };
  return { ...common, kind, accepted: [''] };
}
export default function ContentQuizEditor({ quiz, onChange }: { quiz: EditorQuiz | null; onChange: (quiz: EditorQuiz) => void }) {
  const { t, explanationLanguage: lang } = useLanguage();
  if (!quiz) return <div className="border-t border-border pt-5"><button type="button" className="border border-border rounded-lg p-3" onClick={() => onChange({ kind: 'lesson', passPercent: 80, questions: [newQuestion('choice')] })}>{t('Добавить тест')}</button></div>;
  const update = (index: number, question: EditorQuestion) => onChange({ ...quiz, questions: quiz.questions.map((q, i) => i === index ? question : q) });
  const move = (index: number, delta: number) => { const questions = [...quiz.questions]; [questions[index], questions[index + delta]] = [questions[index + delta], questions[index]]; onChange({ ...quiz, questions }); };
  return <div className="space-y-5 border-t border-border pt-5"><h2 className="text-xl font-bold">{t('Редактор заданий')}</h2>
    <p>{t('Изменение теста требует повторного прохождения урока. История результатов сохраняется.')}</p>
    <label className="block">{t('Тип теста')}<select className={inputClass} value={quiz.kind} onChange={e => onChange({ ...quiz, kind: e.target.value as EditorQuiz['kind'] })}><option value="lesson">{t('Тест урока')}</option><option value="module">{t('Тест модуля')}</option></select></label>
    <label className="block">{t('Порог прохождения, %')}<input className={inputClass} required type="number" min={1} max={100} step={1} value={quiz.passPercent} onChange={e => onChange({ ...quiz, passPercent: Number(e.target.value) })} /></label>
    {quiz.questions.map((q, index) => <article key={q.id} className="border border-border rounded-xl p-4 space-y-4">
      <div className="flex flex-wrap gap-3 items-center"><h3 className="font-bold">{index + 1}. {t(kinds[q.kind])}</h3><button type="button" disabled={index === 0} onClick={() => move(index, -1)}>{t('Вверх')}</button><button type="button" disabled={index === quiz.questions.length - 1} onClick={() => move(index, 1)}>{t('Вниз')}</button><button type="button" disabled={quiz.questions.length === 1} onClick={() => onChange({ ...quiz, questions: quiz.questions.filter((_, i) => i !== index) })}>{t('Удалить задание')}</button></div>
      <TranslationFields label={t('Условие задания')} value={q.prompt} maxLength={4000} onChange={prompt => update(index, { ...q, prompt })} />
      <TranslationFields label={t('Объяснение ответа')} value={q.explanation} maxLength={4000} onChange={explanation => update(index, { ...q, explanation })} />
      {(q.kind === 'choice' || q.kind === 'order') && <div className="space-y-4">{q.options.map((o, oi) => <div key={o.id} className="border-l-4 border-border pl-3 space-y-2">
        <TranslationFields label={`${t('Вариант ответа')} ${oi + 1}`} value={o.text} maxLength={4000} onChange={text => update(index, { ...q, options: q.options.map(v => v.id === o.id ? { ...v, text } : v) })} />
        {q.kind === 'choice' ? <label className="flex gap-2"><input type="radio" name={`correct-${q.id}`} checked={q.correct === o.id} onChange={() => update(index, { ...q, correct: o.id })} />{t('Правильный ответ')}</label> : <label className="block">{t('Место в правильном порядке')}<select className={inputClass} value={q.correct.indexOf(o.id)} onChange={e => { const correct = [...q.correct]; const old = correct.indexOf(o.id); const next = Number(e.target.value); [correct[old], correct[next]] = [correct[next], correct[old]]; update(index, { ...q, correct }); }}>{q.options.map((_, position) => <option key={position} value={position}>{position + 1}</option>)}</select></label>}
        <button type="button" disabled={q.options.length <= 2} onClick={() => { const options = q.options.filter(v => v.id !== o.id); update(index, q.kind === 'choice' ? { ...q, options, correct: q.correct === o.id ? options[0].id : q.correct } : { ...q, options, correct: q.correct.filter(id => id !== o.id) }); }}>{t('Удалить вариант')}</button>
      </div>)}<button type="button" disabled={q.options.length >= 30} onClick={() => { const added = option(); update(index, q.kind === 'choice' ? { ...q, options: [...q.options, added] } : { ...q, options: [...q.options, added], correct: [...q.correct, added.id] }); }}>{t('Добавить вариант')}</button></div>}
      {q.kind === 'match' && <div className="space-y-4"><p>{t('Каждая строка задаёт правильную пару.')}</p>{q.left.map((left, pi) => { const right = q.right.find(o => o.id === q.correct[pi])!; return <div key={left.id} className="border-l-4 border-border pl-3 space-y-2"><TranslationFields label={`${t('Левая часть пары')} ${pi + 1}`} value={left.text} maxLength={4000} onChange={text => update(index, { ...q, left: q.left.map(o => o.id === left.id ? { ...o, text } : o) })} /><TranslationFields label={`${t('Правая часть пары')} ${pi + 1}`} value={right.text} maxLength={4000} onChange={text => update(index, { ...q, right: q.right.map(o => o.id === right.id ? { ...o, text } : o) })} /><button type="button" disabled={q.left.length <= 2} onClick={() => update(index, { ...q, left: q.left.filter(o => o.id !== left.id), right: q.right.filter(o => o.id !== right.id), correct: q.correct.filter((_, i) => i !== pi) })}>{t('Удалить пару')}</button></div>; })}<button type="button" disabled={q.left.length >= 30} onClick={() => { const right = option(); update(index, { ...q, left: [...q.left, option()], right: [...q.right, right], correct: [...q.correct, right.id] }); }}>{t('Добавить пару')}</button></div>}
      {'accepted' in q && <div className="space-y-3"><p>{t('Укажите все допустимые ответы отдельными строками.')}</p>{q.accepted.map((answer, ai) => <div key={ai} className="flex gap-3 items-end"><label className="grow">{t('Допустимый ответ')} {ai + 1}<input required maxLength={500} className={inputClass} value={answer} onChange={e => update(index, { ...q, accepted: q.accepted.map((a, i) => i === ai ? e.target.value : a) })} /></label><button type="button" disabled={q.accepted.length <= 1} onClick={() => update(index, { ...q, accepted: q.accepted.filter((_, i) => i !== ai) })}>{t('Удалить ответ')}</button></div>)}<button type="button" disabled={q.accepted.length >= 30} onClick={() => update(index, { ...q, accepted: [...q.accepted, ''] })}>{t('Добавить ответ')}</button></div>}
      {q.kind === 'dictation' && <MediaPicker onSelect={asset => update(index, { ...q, audioUrl: asset.audioUrl, author: asset.author, license: asset.license, sourceUrl: asset.sourceUrl, licenseUrl: asset.licenseUrl })} />}
      {q.kind === 'dictation' && (['audioUrl', 'sourceUrl', 'author', 'license', 'licenseUrl'] as const).map(key => <label className="block" key={key}>{t({ audioUrl: 'Ссылка на аудио', sourceUrl: 'Источник аудио', author: 'Автор', license: 'Лицензия', licenseUrl: 'Ссылка на лицензию' }[key])}<input required type={key.endsWith('Url') && key !== 'audioUrl' ? 'url' : 'text'} pattern={key === 'audioUrl' ? '(https://.*|/api/media/[0-9a-f-]+/file)' : key.endsWith('Url') ? 'https://.*' : undefined} maxLength={key.endsWith('Url') ? 2000 : 200} className={inputClass} value={q[key]} onChange={e => update(index, { ...q, [key]: e.target.value })} /></label>)}
    </article>)}
    <div className="flex flex-wrap gap-3">{(Object.keys(kinds) as EditorQuestion['kind'][]).map(kind => <button type="button" disabled={quiz.questions.length >= 30} className="border border-border rounded-lg p-3" key={kind} onClick={() => onChange({ ...quiz, questions: [...quiz.questions, newQuestion(kind)] })}>{t('Добавить задание')}: {t(kinds[kind])}</button>)}</div>
    <details className="border border-border rounded-xl p-4"><summary>{t('Предпросмотр заданий и ответов')}</summary><ol className="space-y-4 mt-4">{quiz.questions.map((q, i) => <li key={q.id}><h3 className="font-bold">{i + 1}. {q.prompt[lang]}</h3>{'options' in q && <ul>{q.options.map(o => <li key={o.id}>{o.text[lang]}</li>)}</ul>}{q.kind === 'dictation' && <><audio controls preload="none" aria-label={q.prompt[lang]} src={isAudioUrl(q.audioUrl) ? q.audioUrl : undefined} /><p>{q.author} · {q.license}</p></>}
    <p>{t('Правильный ответ')}: {q.kind === 'choice' ? q.options.find(o => o.id === q.correct)?.text[lang] : q.kind === 'order' ? q.correct.map(id => q.options.find(o => o.id === id)?.text[lang]).join(' → ') : q.kind === 'match' ? q.left.map((left, n) => `${left.text[lang]} → ${q.right.find(o => o.id === q.correct[n])?.text[lang]}`).join('; ') : q.accepted.join(' / ')}</p><p>{q.explanation[lang]}</p></li>)}</ol></details>
  </div>;
}
