import VocabularyCsv from './VocabularyCsv';
import MediaPicker from './MediaPicker';
import type { ContentBlock } from '../api/content';
import { useLanguage } from '../i18n/LanguageProvider';

export const emptyTranslation = () => ({ ru: '', kk: '', en: '' });
type Localized = ReturnType<typeof emptyTranslation>;
const inputClass = 'block w-full border border-border bg-background rounded-lg p-2';
export function TranslationFields({ label, value, onChange, maxLength = 8000 }: { label: string; value: Localized; onChange: (value: Localized) => void; maxLength?: number }) {
  return <div className="grid gap-2 md:grid-cols-3">{(['ru', 'kk', 'en'] as const).map(key => <label key={key}>{label} · {key}<textarea required maxLength={maxLength} className={inputClass} value={value[key]} onChange={e => onChange({ ...value, [key]: e.target.value })} /></label>)}</div>;
}
export default function ContentBlocksEditor({ blocks, onChange }: { blocks: ContentBlock[]; onChange: (blocks: ContentBlock[]) => void }) {
  const { t } = useLanguage();
  const update = (index: number, content: ContentBlock['content']) => onChange(blocks.map((b, i) => i === index ? { ...b, content } : b));
  const add = (kind: ContentBlock['kind']) => {
    const phrase = { hanzi: '', pinyin: '', translation: emptyTranslation() };
    const content = kind === 'vocabulary' ? { title: emptyTranslation(), words: [phrase] } : kind === 'reading' ? { title: emptyTranslation(), text: emptyTranslation(), ...phrase } : { title: emptyTranslation(), ...phrase, audioUrl: '', sourceUrl: '', author: '', license: '', licenseUrl: '' };
    onChange([...blocks, { id: crypto.randomUUID(), kind, content }]);
  };
  const move = (index: number, delta: number) => { const next = [...blocks]; [next[index], next[index + delta]] = [next[index + delta], next[index]]; onChange(next); };
  return <div className="space-y-5"><h2 className="text-xl font-bold">{t('Блоки урока')}</h2>{blocks.map((block, index) => <article key={block.id} className="border border-border rounded-xl p-4 space-y-3">
    <div className="flex flex-wrap gap-3 items-center"><h3 className="font-bold">{index + 1}. {t({ reading: 'Текстовый блок', vocabulary: 'Словарный блок', audio: 'Аудиоблок' }[block.kind])}</h3><button type="button" disabled={index === 0} onClick={() => move(index, -1)}>{t('Вверх')}</button><button type="button" disabled={index === blocks.length - 1} onClick={() => move(index, 1)}>{t('Вниз')}</button><button type="button" onClick={() => onChange(blocks.filter((_, i) => i !== index))}>{t('Удалить блок')}</button></div>
    <TranslationFields label={t('Название блока')} maxLength={200} value={block.content.title} onChange={title => update(index, { ...block.content, title })} />
    {block.kind === 'reading' && <TranslationFields label={t('Текст')} maxLength={16000} value={block.content.text ?? emptyTranslation()} onChange={text => update(index, { ...block.content, text })} />}
    {block.kind !== 'vocabulary' && <><label className="block">{t('Иероглифы')}<textarea required maxLength={4000} className={inputClass} value={block.content.hanzi ?? ''} onChange={e => update(index, { ...block.content, hanzi: e.target.value })} /></label><label className="block">{t('Пиньинь')}<input required maxLength={8000} className={inputClass} value={block.content.pinyin ?? ''} onChange={e => update(index, { ...block.content, pinyin: e.target.value })} /></label><TranslationFields label={t('Перевод')} value={block.content.translation ?? emptyTranslation()} onChange={translation => update(index, { ...block.content, translation })} /></>}
    {block.kind === 'vocabulary' && <><VocabularyCsv words={block.content.words ?? []} onChange={words => update(index, { ...block.content, words })} />{block.content.words?.map((word, wi) => <div key={wi} className="border-l-4 border-border pl-3 space-y-2"><label className="block">{t('Иероглифы')}<input required maxLength={4000} className={inputClass} value={word.hanzi} onChange={e => update(index, { ...block.content, words: block.content.words!.map((w, i) => i === wi ? { ...w, hanzi: e.target.value } : w) })} /></label><label className="block">{t('Пиньинь')}<input required maxLength={8000} className={inputClass} value={word.pinyin} onChange={e => update(index, { ...block.content, words: block.content.words!.map((w, i) => i === wi ? { ...w, pinyin: e.target.value } : w) })} /></label><TranslationFields label={t('Перевод')} value={word.translation} onChange={translation => update(index, { ...block.content, words: block.content.words!.map((w, i) => i === wi ? { ...w, translation } : w) })} /><button type="button" disabled={block.content.words!.length === 1} onClick={() => update(index, { ...block.content, words: block.content.words!.filter((_, i) => i !== wi) })}>{t('Удалить слово')}</button></div>)}<button type="button" disabled={(block.content.words?.length ?? 0) >= 100} onClick={() => update(index, { ...block.content, words: [...(block.content.words ?? []), { hanzi: '', pinyin: '', translation: emptyTranslation() }] })}>{t('Добавить слово')}</button></>}
    {block.kind === 'audio' && <MediaPicker onSelect={asset => update(index, { ...block.content, audioUrl: asset.audioUrl, author: asset.author, license: asset.license, sourceUrl: asset.sourceUrl, licenseUrl: asset.licenseUrl })} />}
    {block.kind === 'audio' && (['audioUrl', 'sourceUrl', 'author', 'license', 'licenseUrl'] as const).map(key => <label className="block" key={key}>{t({ audioUrl: 'Ссылка на аудио', sourceUrl: 'Источник аудио', author: 'Автор', license: 'Лицензия', licenseUrl: 'Ссылка на лицензию' }[key])}<input required type={key.endsWith('Url') && key !== 'audioUrl' ? 'url' : 'text'} maxLength={key.endsWith('Url') ? 2000 : 200} pattern={key === 'audioUrl' ? '(https://.*|/api/media/[0-9a-f-]+/file)' : key.endsWith('Url') ? 'https://.*' : undefined} className={inputClass} value={block.content[key] ?? ''} onChange={e => update(index, { ...block.content, [key]: e.target.value })} /></label>)}
  </article>)}<div className="flex flex-wrap gap-3">{(['vocabulary', 'reading', 'audio'] as const).map(kind => <button type="button" disabled={blocks.length >= 40} className="border border-border rounded-lg p-3" key={kind} onClick={() => add(kind)}>{t({ vocabulary: 'Добавить словарный блок', reading: 'Добавить текстовый блок', audio: 'Добавить аудиоблок' }[kind])}</button>)}</div></div>;
}
